---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: public/data
  label: Documenten
  create: all
  match: "**/*"
  new_doc_ext: json
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: npm run deploy
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: build
  output_directory: build
  instant_preview_command: npm run build
